In [1]:
import fastf1.core
import fastf1.plotting
import pandas as pd
import numpy as np
from sqlalchemy.dialects.sqlite import insert
from sqlalchemy import select
from backend.database.db_init import ENGINE
from sqlalchemy.orm import sessionmaker
from backend.database.models import EventSession, EventRound, SessionName, Weather, RaceControl, Lap, Driver
#from backend.modules.db_tools import get_data_for_event_session, insert_for_weather, get_race_control_messages, get_lap_data
from IPython.display import clear_output
import fastf1
import os
from dotenv import load_dotenv
load_dotenv()

Session = sessionmaker(bind=ENGINE)

year = 2025
gp = 1

session_data = fastf1.get_session(year, gp, 5)
session_data.load()

req         WARNING 	DEFAULT CACHE ENABLED! (32.54 GB) /home/kurios/.cache/fastf1
core           INFO 	Loading data for Australian Grand Prix - Race [v3.7.0]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '87'
core        WARNING 	Fixed incorrect tyre stint information for driver '30'
core        WARNING 	Fixed incorrect tyre stint information for driver '5'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core        WARNING 	Driver 4 completed the race distance 00:00.022000 before the recorded end of the session.
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '63', '12', '23', '18', '27', '16', '81', '44', '10', '22', '31', '87', '30', '5', '14', '55', '7', '6']

In [ ]:
def get_event_session(session, year, round_number, session_name):
    stmt_event_session = (
        select(EventSession)
            .join(EventRound)
            .join(SessionName)
            .filter(EventRound.year == year)
            .filter(EventRound.round_number == round_number)
            .filter(SessionName.name == session_name)
    )
    return session.execute(stmt_event_session).scalars().all()

def get_list_drivers(session, results_event_session):
    stmt_drivers = (
        select(Lap)
            .join(Driver)
            .join(EventSession)
            .filter(EventSession.id == results_event_session[0].id)
    )
    return session.execute(stmt_drivers).scalars().unique()

def get_lap_per_driver(session, results_event_session, driver):
    stmt_driver = (
    select(Lap)
        .join(Driver)
        .join(EventSession)
        .filter(EventSession.id == results_event_session[0].id)
        .filter(Driver.number == driver)
    )
    return session.execute(stmt_driver).scalars().unique()

def format_car_data(telemetry):
    df = telemetry.copy()
    
    try:
        df = df.add_distance().add_differential_distance().add_relative_distance().add_track_status()
    except Exception:
        pass

    df['time_ms'] = (df['Time'].dt.total_seconds() * 1000).astype(int)
    df['date'] = pd.to_datetime(df['Date']).dt.date
    
    df['isBraking'] = df['Brake'].astype(bool)
    df['rpm'] = df['RPM'].fillna(0).astype(int)
    df['speed'] = df['Speed'].fillna(0).astype(int)
    df['throttle'] = df['Throttle'].fillna(0).astype(int)
    df['track_status'] = df['TrackStatus'].fillna(0).astype(int)
    
    mapping = {
        'rpm': 'rpm', 'speed': 'speed', 'nGear': 'gear', 'throttle': 'throttle',
        'isBraking': 'isBraking', 'time_ms': 'time_ms', 'Distance': 'distance',
        'DifferentialDistance': 'differential_distance', 'RelativeDistance': 'relative_distance',
        'TrackStatus': 'track_status'
    }
    
    existing_cols = [c for c in mapping.keys() if c in df.columns]
    return df[existing_cols].rename(columns=mapping)

def format_pos_data(telemetry):
    df = telemetry.copy()
    
    try:
        df = df.add_track_status()
    except Exception:
        pass

    df['Time'] = df['Time'].apply(lambda x: int(x.total_seconds()*1000) if pd.notna(x) else None)
    df['Date'] = pd.to_datetime(df['Date']).dt.date

    df['SessionTime'] = pd.to_timedelta(df['SessionTime'])
    df['SessionTime'] = df['SessionTime'].apply(lambda x: x.to_pytimedelta() if pd.notna(x) else None)

    df = df.replace({pd.NaT: None, np.nan: None}).copy()
    int_cols = ['X', 'Y', 'Z', 'Time', 'TrackStatus']
    for col in int_cols:
        df[col] = df[col].apply(lambda x: int(x) if pd.notna(x) else 0)

    mapping = {
            'X': 'x',
            'Y': 'y',
            'Z': 'z',
            'Time': 'time_ms',
            'SessionTime': 'session_time',
            'Date': 'date',
            'Status': 'is_on_track',
            'TrackStatus': 'track_status'
            }

    existing_cols = [c for c in mapping.keys() if c in df.columns]
    return df[existing_cols].rename(columns=mapping)

In [ ]:
laps = session_data.laps

all_drivers_car_data = []
all_drivers_pos_data = []

with Session() as session:
    results_event_session = get_event_session(session, 2025, 5, 'Race')
    results_drivers = get_list_drivers(session, results_event_session)
    list_drivers = list(set([ld.driver.number for ld in results_drivers]))

    for driver_num in list_drivers:

        driver_laps = laps.pick_drivers(driver_num)

        if driver_laps.empty:
            print(f"Skipping Driver {driver_num}: Not found in FastF1 laps data.")
            continue

        results = get_lap_per_driver(session, results_event_session, driver_num)
        
        for lap_obj in results:
            lap_slice = driver_laps.pick_laps(lap_obj.lap_number)

            if lap_slice.empty:
                print(
                    f"Skipping Driver {driver_num} Lap {lap_obj.lap_number}: "
                    "Lap not present in FastF1."
                )
                continue

            try:
                raw_car_slice = lap_slice.get_car_data()
                raw_pos_slice = lap_slice.get_pos_data()
            except ValueError as e:
                print(
                    f"Skipping Driver {driver_num} Lap {lap_obj.lap_number}: {e}"
                )
                continue

            if raw_car_slice.empty or raw_pos_slice.empty:
                print(
                    f"Skipping Driver {driver_num} Lap {lap_obj.lap_number}: "
                    "No telemetry recorded."
                )
                continue

            car_data = format_car_data(raw_car_slice) 
            pos_data = format_pos_data(raw_pos_slice)
            
            car_data['lap_id'] = lap_obj.id
            pos_data['lap_id'] = lap_obj.id

            all_drivers_car_data.append(car_data)
            all_drivers_pos_data.append(pos_data)

if all_drivers_car_data:
    final_car_df = pd.concat(all_drivers_car_data, ignore_index=True)
    
if all_drivers_pos_data:
    final_pos_df = pd.concat(all_drivers_pos_data, ignore_index=True)

2025-12-27 23:17:52,169 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2025-12-27 23:17:52,171 INFO sqlalchemy.engine.Engine SELECT event_session.id, event_session.date, event_session.event_round_id, event_session.session_name_id
FROM event_session JOIN event_round ON event_round.id = event_session.event_round_id JOIN session_name ON session_name.id = event_session.session_name_id
WHERE event_round.year = ? AND event_round.round_number = ? AND session_name.name = ?
2025-12-27 23:17:52,171 INFO sqlalchemy.engine.Engine [cached since 343.2s ago] (2025, 5, 'Race')
2025-12-27 23:17:52,173 INFO sqlalchemy.engine.Engine SELECT lap.id, lap.laptime_ms, lap.lap_number, lap.sector_1_ms, lap.sector_2_ms, lap.sector_3_ms, lap.stint, lap.speed_i1, lap.speed_i2, lap.speed_fl, lap.speed_st, lap.tyre_life, lap.position, lap.sector_1_time, lap.sector_2_time, lap.sector_3_time, lap.pit_in_time_ms, lap.pit_out_time_ms, lap.start_time, lap.start_date, lap.is_personal_best, lap.is_deleted, lap.is_accurate, lap.track_status, lap.event_session_id, lap.driver_id, lap.team_id, lap.tyre_id
FROM lap JOIN driver ON driver.id = lap.driver_id JOIN event_session ON event_session.id = lap.event_session_id
WHERE event_session.id = ?
2025-12-27 23:17:52,174 INFO sqlalchemy.engine.Engine [cached since 343.2s ago] (5,)
2025-12-27 23:17:52,199 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,200 INFO sqlalchemy.engine.Engine [cached since 343.2s ago] (30,)
2025-12-27 23:17:52,202 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,202 INFO sqlalchemy.engine.Engine [cached since 343.2s ago] (27,)
2025-12-27 23:17:52,205 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,205 INFO sqlalchemy.engine.Engine [cached since 343.2s ago] (9,)
2025-12-27 23:17:52,207 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,208 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (23,)
2025-12-27 23:17:52,210 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,210 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (18,)
2025-12-27 23:17:52,212 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,212 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (3,)
2025-12-27 23:17:52,214 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,214 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (24,)
2025-12-27 23:17:52,216 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,217 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (8,)
2025-12-27 23:17:52,218 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,219 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (1,)
2025-12-27 23:17:52,221 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,222 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (19,)
2025-12-27 23:17:52,225 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,226 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (14,)
2025-12-27 23:17:52,229 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,230 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (25,)
2025-12-27 23:17:52,232 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,232 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (29,)
2025-12-27 23:17:52,234 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,235 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (12,)
2025-12-27 23:17:52,237 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,238 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (28,)
2025-12-27 23:17:52,240 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,240 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (22,)
2025-12-27 23:17:52,242 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,243 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (20,)
2025-12-27 23:17:52,245 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,246 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (17,)
2025-12-27 23:17:52,248 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,249 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (35,)
2025-12-27 23:17:52,250 INFO sqlalchemy.engine.Engine SELECT driver.id AS driver_id, driver.name AS driver_name, driver.number AS driver_number, driver.abbreviation AS driver_abbreviation, driver.country AS driver_country, driver.hex_code AS driver_hex_code
FROM driver
WHERE driver.id = ?
2025-12-27 23:17:52,251 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (33,)
2025-12-27 23:17:52,255 INFO sqlalchemy.engine.Engine SELECT lap.id, lap.laptime_ms, lap.lap_number, lap.sector_1_ms, lap.sector_2_ms, lap.sector_3_ms, lap.stint, lap.speed_i1, lap.speed_i2, lap.speed_fl, lap.speed_st, lap.tyre_life, lap.position, lap.sector_1_time, lap.sector_2_time, lap.sector_3_time, lap.pit_in_time_ms, lap.pit_out_time_ms, lap.start_time, lap.start_date, lap.is_personal_best, lap.is_deleted, lap.is_accurate, lap.track_status, lap.event_session_id, lap.driver_id, lap.team_id, lap.tyre_id
FROM lap JOIN driver ON driver.id = lap.driver_id JOIN event_session ON event_session.id = lap.event_session_id
WHERE event_session.id = ? AND driver.number = ?
2025-12-27 23:17:52,256 INFO sqlalchemy.engine.Engine [cached since 343.3s ago] (5, 1)
2025-12-27 23:17:53,754 INFO sqlalchemy.engine.Engine SELECT lap.id, lap.laptime_ms, lap.lap_number, lap.sector_1_ms, lap.sector_2_ms, lap.sector_3_ms, lap.stint, lap.speed_i1, lap.speed_i2, lap.speed_fl, lap.speed_st, lap.tyre_life, lap.position, lap.sector_1_time, lap.sector_2_time, lap.sector_3_time, lap.pit_in_time_ms, lap.pit_out_time_ms, lap.start_time, lap.start_date, lap.is_personal_best, lap.is_deleted, lap.is_accurate, lap.track_status, lap.event_session_id, lap.driver_id, lap.team_id, lap.tyre_id
FROM lap JOIN driver ON driver.id = lap.driver_id JOIN event_session ON event_session.id = lap.event_session_id
WHERE event_session.id = ? AND driver.number = ?
2025-12-27 23:17:53,754 INFO sqlalchemy.engine.Engine [cached since 344.8s ago] (5, 4)
2025-12-27 23:17:55,209 INFO sqlalchemy.engine.Engine SELECT lap.id, lap.laptime_ms, lap.lap_number, lap.sector_1_ms, lap.sector_2_ms, lap.sector_3_ms, lap.stint, lap.speed_i1, lap.speed_i2, lap.speed_fl, lap.speed_st, lap.tyre_life, lap.position, lap.sector_1_time, lap.sector_2_time, lap.sector_3_time, lap.pit_in_time_ms, lap.pit_out_time_ms, lap.start_time, lap.start_date, lap.is_personal_best, lap.is_deleted, lap.is_accurate, lap.track_status, lap.event_session_id, lap.driver_id, lap.team_id, lap.tyre_id
FROM lap JOIN driver ON driver.id = lap.driver_id JOIN event_session ON event_session.id = lap.event_session_id
WHERE event_session.id = ? AND driver.number = ?
2025-12-27 23:17:55,209 INFO sqlalchemy.engine.Engine [cached since 346.2s ago] (5, 5)
Skipping Driver 5 Lap 47: Lap not present in FastF1.
Skipping Driver 5 Lap 48: Lap not present in FastF1.
Skipping Driver 5 Lap 49: Lap not present in FastF1.
2025-12-27 23:17:56,570 INFO sqlalchemy.engine.Engine SELECT lap.id, lap.laptime_ms, lap.lap_number, lap.sector_1_ms, lap.sector_2_ms, lap.sector_3_ms, lap.stint, lap.speed_i1, lap.speed_i2, lap.speed_fl, lap.speed_st, lap.tyre_life, lap.position, lap.sector_1_time, lap.sector_2_time, lap.sector_3_time, lap.pit_in_time_ms, lap.pit_out_time_ms, lap.start_time, lap.start_date, lap.is_personal_best, lap.is_deleted, lap.is_accurate, lap.track_status, lap.event_session_id, lap.driver_id, lap.team_id, lap.tyre_id
FROM lap JOIN driver ON driver.id = lap.driver_id JOIN event_session ON event_session.id = lap.event_session_id
WHERE event_session.id = ? AND driver.number = ?
2025-12-27 23:17:56,570 INFO sqlalchemy.engine.Engine [cached since 347.6s ago] (5, 6)
Skipping Driver 6 Lap 2: Lap not present in FastF1.
Skipping Driver 6 Lap 3: Lap not present in FastF1.
Skipping Driver 6 Lap 4: Lap not present in FastF1.
Skipping Driver 6 Lap 5: Lap not present in FastF1.
Skipping Driver 6 Lap 6: Lap not present in FastF1.
Skipping Driver 6 Lap 7: Lap not present in FastF1.
Skipping Driver 6 Lap 8: Lap not present in FastF1.
Skipping Driver 6 Lap 9: Lap not present in FastF1.
Skipping Driver 6 Lap 10: Lap not present in FastF1.
Skipping Driver 6 Lap 11: Lap not present in FastF1.
Skipping Driver 6 Lap 12: Lap not present in FastF1.
Skipping Driver 6 Lap 13: Lap not present in FastF1.
Skipping Driver 6 Lap 14: Lap not present in FastF1.
Skipping Driver 6 Lap 15: Lap not present in FastF1.
Skipping Driver 6 Lap 16: Lap not present in FastF1.
Skipping Driver 6 Lap 17: Lap not present in FastF1.
Skipping Driver 6 Lap 18: Lap not present in FastF1.
Skipping Driver 6 Lap 19: Lap not present in FastF1.
Skipping Driver 6 Lap 20: Lap not present in FastF1.
Skipping Driver 6 Lap 21: Lap not present in FastF1.
Skipping Driver 6 Lap 22: Lap not present in FastF1.
Skipping Driver 6 Lap 23: Lap not present in FastF1.
Skipping Driver 6 Lap 24: Lap not present in FastF1.
Skipping Driver 6 Lap 25: Lap not present in FastF1.
Skipping Driver 6 Lap 26: Lap not present in FastF1.
Skipping Driver 6 Lap 27: Lap not present in FastF1.
Skipping Driver 6 Lap 28: Lap not present in FastF1.
Skipping Driver 6 Lap 29: Lap not present in FastF1.
Skipping Driver 6 Lap 30: Lap not present in FastF1.
Skipping Driver 6 Lap 31: Lap not present in FastF1.
Skipping Driver 6 Lap 32: Lap not present in FastF1.
Skipping Driver 6 Lap 33: Lap not present in FastF1.
Skipping Driver 6 Lap 34: Lap not present in FastF1.
Skipping Driver 6 Lap 35: Lap not present in FastF1.
Skipping Driver 6 Lap 36: Lap not present in FastF1.
Skipping Driver 6 Lap 37: Lap not present in FastF1.
Skipping Driver 6 Lap 38: Lap not present in FastF1.
Skipping Driver 6 Lap 39: Lap not present in FastF1.
Skipping Driver 6 Lap 40: Lap not present in FastF1.
Skipping Driver 6 Lap 41: Lap not present in FastF1.
Skipping Driver 6 Lap 42: Lap not present in FastF1.
Skipping Driver 6 Lap 43: Lap not present in FastF1.
Skipping Driver 6 Lap 44: Lap not present in FastF1.
Skipping Driver 6 Lap 45: Lap not present in FastF1.
Skipping Driver 6 Lap 46: Lap not present in FastF1.
Skipping Driver 6 Lap 47: Lap not present in FastF1.
Skipping Driver 6 Lap 48: Lap not present in FastF1.
Skipping Driver 6 Lap 49: Lap not present in FastF1.
Skipping Driver 6 Lap 50: Lap not present in FastF1.
2025-12-27 23:17:56,616 INFO sqlalchemy.engine.Engine SELECT lap.id, lap.laptime_ms, lap.lap_number, lap.sector_1_ms, lap.sector_2_ms, lap.sector_3_ms, lap.stint, lap.speed_i1, lap.speed_i2, lap.speed_fl, lap.speed_st, lap.tyre_life, lap.position, lap.sector_1_time, lap.sector_2_time, lap.sector_3_time, lap.pit_in_time_ms, lap.pit_out_time_ms, lap.start_time, lap.start_date, lap.is_personal_best, lap.is_deleted, lap.is_accurate, lap.track_status, lap.event_session_id, lap.driver_id, lap.team_id, lap.tyre_id
FROM lap JOIN driver ON driver.id = lap.driver_id JOIN event_session ON event_session.id = lap.event_session_id
WHERE event_session.id = ? AND driver.number = ?
2025-12-27 23:17:56,616 INFO sqlalchemy.engine.Engine [cached since 347.6s ago] (5, 7)
Skipping Driver 7 Lap 2: Lap not present in FastF1.
Skipping Driver 7 Lap 3: Lap not present in FastF1.
Skipping Driver 7 Lap 4: Lap not present in FastF1.
Skipping Driver 7 Lap 5: Lap not present in FastF1.
Skipping Driver 7 Lap 6: Lap not present in FastF1.
Skipping Driver 7 Lap 7: Lap not present in FastF1.
Skipping Driver 7 Lap 8: Lap not present in FastF1.
Skipping Driver 7 Lap 9: Lap not present in FastF1.
Skipping Driver 7 Lap 10: Lap not present in FastF1.
Skipping Driver 7 Lap 11: Lap not present in FastF1.
Skipping Driver 7 Lap 12: Lap not present in FastF1.
Skipping Driver 7 Lap 13: Lap not present in FastF1.
Skipping Driver 7 Lap 14: Lap not present in FastF1.
Skipping Driver 7 Lap 15: Lap not present in FastF1.
Skipping Driver 7 Lap 16: Lap not present in FastF1.
Skipping Driver 7 Lap 17: Lap not present in FastF1.
Skipping Driver 7 Lap 18: Lap not present in FastF1.
Skipping Driver 7 Lap 19: Lap not present in FastF1.
Skipping Driver 7 Lap 20: Lap not present in FastF1.
Skipping Driver 7 Lap 21: Lap not present in FastF1.
Skipping Driver 7 Lap 22: Lap not present in FastF1.
Skipping Driver 7 Lap 23: Lap not present in FastF1.
Skipping Driver 7 Lap 24: Lap not present in FastF1.
Skipping Driver 7 Lap 25: Lap not present in FastF1.
Skipping Driver 7 Lap 26: Lap not present in FastF1.
Skipping Driver 7 Lap 27: Lap not present in FastF1.
Skipping Driver 7 Lap 28: Lap not present in FastF1.
Skipping Driver 7 Lap 29: Lap not present in FastF1.
Skipping Driver 7 Lap 30: Lap not present in FastF1.
Skipping Driver 7 Lap 31: Lap not present in FastF1.
Skipping Driver 7 Lap 32: Lap not present in FastF1.
Skipping Driver 7 Lap 33: Lap not present in FastF1.
Skipping Driver 7 Lap 34: Lap not present in FastF1.
Skipping Driver 7 Lap 35: Lap not present in FastF1.
Skipping Driver 7 Lap 36: Lap not present in FastF1.
Skipping Driver 7 Lap 37: Lap not present in FastF1.
Skipping Driver 7 Lap 38: Lap not present in FastF1.
Skipping Driver 7 Lap 39: Lap not present in FastF1.
Skipping Driver 7 Lap 40: Lap not present in FastF1.
Skipping Driver 7 Lap 41: Lap not present in FastF1.
Skipping Driver 7 Lap 42: Lap not present in FastF1.
Skipping Driver 7 Lap 43: Lap not present in FastF1.
Skipping Driver 7 Lap 44: Lap not present in FastF1.
Skipping Driver 7 Lap 45: Lap not present in FastF1.
Skipping Driver 7 Lap 46: Lap not present in FastF1.
Skipping Driver 7 Lap 47: Lap not present in FastF1.
Skipping Driver 7 Lap 48: Lap not present in FastF1.
Skipping Driver 7 Lap 49: Lap not present in FastF1.
2025-12-27 23:17:56,661 INFO sqlalchemy.engine.Engine SELECT lap.id, lap.laptime_ms, lap.lap_number, lap.sector_1_ms, lap.sector_2_ms, lap.sector_3_ms, lap.stint, lap.speed_i1, lap.speed_i2, lap.speed_fl, lap.speed_st, lap.tyre_life, lap.position, lap.sector_1_time, lap.sector_2_time, lap.sector_3_time, lap.pit_in_time_ms, lap.pit_out_time_ms, lap.start_time, lap.start_date, lap.is_personal_best, lap.is_deleted, lap.is_accurate, lap.track_status, lap.event_session_id, lap.driver_id, lap.team_id, lap.tyre_id
FROM lap JOIN driver ON driver.id = lap.driver_id JOIN event_session ON event_session.id = lap.event_session_id
WHERE event_session.id = ? AND driver.number = ?
2025-12-27 23:17:56,662 INFO sqlalchemy.engine.Engine [cached since 347.7s ago] (5, 10)
2025-12-27 23:17:56,694 INFO sqlalchemy.engine.Engine SELECT lap.id, lap.laptime_ms, lap.lap_number, lap.sector_1_ms, lap.sector_2_ms, lap.sector_3_ms, lap.stint, lap.speed_i1, lap.speed_i2, lap.speed_fl, lap.speed_st, lap.tyre_life, lap.position, lap.sector_1_time, lap.sector_2_time, lap.sector_3_time, lap.pit_in_time_ms, lap.pit_out_time_ms, lap.start_time, lap.start_date, lap.is_personal_best, lap.is_deleted, lap.is_accurate, lap.track_status, lap.event_session_id, lap.driver_id, lap.team_id, lap.tyre_id
FROM lap JOIN driver ON driver.id = lap.driver_id JOIN event_session ON event_session.id = lap.event_session_id
WHERE event_session.id = ? AND driver.number = ?
2025-12-27 23:17:56,694 INFO sqlalchemy.engine.Engine [cached since 347.7s ago] (5, 12)
2025-12-27 23:17:58,164 INFO sqlalchemy.engine.Engine SELECT lap.id, lap.laptime_ms, lap.lap_number, lap.sector_1_ms, lap.sector_2_ms, lap.sector_3_ms, lap.stint, lap.speed_i1, lap.speed_i2, lap.speed_fl, lap.speed_st, lap.tyre_life, lap.position, lap.sector_1_time, lap.sector_2_time, lap.sector_3_time, lap.pit_in_time_ms, lap.pit_out_time_ms, lap.start_time, lap.start_date, lap.is_personal_best, lap.is_deleted, lap.is_accurate, lap.track_status, lap.event_session_id, lap.driver_id, lap.team_id, lap.tyre_id

In [21]:
final_car_df

,rpm,speed,gear,throttle,isBraking,time_ms,distance,differential_distance,relative_distance,track_status,lap_id
0,10043,0,2,16,True,119,0.000000,0.000000,0.000000,1,1563
1,9752,0,2,16,True,398,0.000000,0.000000,0.000000,1,1563
2,8072,0,2,16,False,638,0.000000,0.000000,0.000000,1,1563
3,6392,8,2,16,False,878,0.533333,0.533333,0.000101,1,1563
4,4992,13,2,16,False,1078,1.255556,0.722222,0.000238,1,1563
...,...,...,...,...,...,...,...,...,...,...,...
294966,10869,275,7,100,False,94997,5168.965556,15.201389,0.985189,4,2162
294967,10959,277,7,100,False,95318,5193.664722,24.699167,0.989896,4,2162
294968,11077,279,7,100,False,95598,5215.364722,21.700000,0.994032,4,2162
294969,11148,281,7,100,False,95838,5234.098056,18.733333,0.997603,4,2162
294970,11231,283,7,100,False,95998,5246.675833,12.577778,1.000000,4,2162

In [22]:
final_pos_df

,x,y,z,time_ms,session_time,date,is_on_track,track_status,lap_id
0,-941,-1576,86,194,0 days 01:11:00.549000,2025-03-16,OnTrack,1,1563
1,-941,-1576,86,574,0 days 01:11:00.929000,2025-03-16,OnTrack,1,1563
2,-943,-1573,86,774,0 days 01:11:01.129000,2025-03-16,OnTrack,1,1563
3,-951,-1567,86,1174,0 days 01:11:01.529000,2025-03-16,OnTrack,1,1563
4,-956,-1562,86,1334,0 days 01:11:01.689000,2025-03-16,OnTrack,1,1563
...,...,...,...,...,...,...,...,...,...
301728,-412,-2077,90,94740,0 days 02:43:03.689000,2025-03-16,OnTrack,4,2162
301729,-643,-1858,88,95020,0 days 02:43:03.969000,2025-03-16,OnTrack,4,2162
301730,-799,-1710,88,95440,0 days 02:43:04.389000,2025-03-16,OnTrack,4,2162
301731,-929,-1587,86,95620,0 days 02:43:04.569000,2025-03-16,OnTrack,4,2162
301732,-1044,-1477,86,95940,0 days 02:43:04.889000,2025-03-16,OnTrack,4,2162