In [1]:
import fastf1
import fastf1.core
import fastf1.plotting
import pandas as pd
from IPython.display import clear_output

In [ ]:
import fastf1
import fastf1.core
import fastf1.plotting
import pandas as pd
from IPython.display import clear_output

In [2]:
session_name = [{"name": "Practice 1"}, {"name": "Practice 2"}, {"name": "Practice 3"}, {"name": "Sprint Qualifying"}, {"name": "Sprint"}, {"name": "Qualifying"}, {"name": "Race"}]
compound = [{"hardness": "C0"}, {"hardness": "C1"}, {"hardness": "C2"}, {"hardness": "C3"}, {"hardness": "C4"}, {"hardness": "C5"}, {"hardness": "C6"}]
tyre = [{"name": "soft"}, {"name": "medium"}, {"name": "hard"}, {"name": "intermediate"}, {"name": "wet"}, {"name": "unknown"}, ]
drs = [{"status" : "Off"}, {"status" : "Unknown"}, {"status" : "Detected"}, {"status" : "On"}]
wind_direction = [{"cardinal_direction": "N"}, {"cardinal_direction": "NNE"}, {"cardinal_direction": "NE"}, {"cardinal_direction": "ENE"}, {"cardinal_direction": "E"}, {"cardinal_direction": "ESE"}, {"cardinal_direction": "SE"}, {"cardinal_direction": "SSE"}, {"cardinal_direction": "S"}, {"cardinal_direction": "SSW"}, {"cardinal_direction": "SW"}, {"cardinal_direction": "WSW"}, {"cardinal_direction": "W"}, {"cardinal_direction": "WNW"}, {"cardinal_direction": "NW"}, {"cardinal_direction": "NNW"}]

In [10]:
df_final = pd.DataFrame()
for round in range(1,25):
    for event_session in [1,4,5]:
        session = fastf1.get_session(2025, round, event_session)
        session.load(telemetry=False, weather=False, messages=False)

        drivers = fastf1.plotting.list_driver_names(session=session)
        drivers_abbreviation =[fastf1.plotting.get_driver_abbreviation(driver, session) for driver in drivers]
        df = pd.DataFrame([session.get_driver(abbreviation) for abbreviation in drivers_abbreviation])
        df = df[['DriverNumber', 'Abbreviation', 'FullName', 'TeamColor']].rename(columns={'DriverNumber':'number', 'Abbreviation':'abbreviation', 'FullName':'name', 'TeamColor':'hex_code'})
        df_final = pd.concat([df, df_final]).drop_duplicates()

drivers_data_manual = [{"name" : "Max Verstappen", "country":"Dutchland"},
        {"name" : "Yuki Tsunoda", "country":"Japan"},
        {"name" : "Arvid Lindblad", "country":"Great Britain"},
        {"name" : "Pierre Gasly", "country":"France"},
        {"name" : "Franco Colapinto", "country":"Argentine"},
        {"name" : "Kimi Antonelli", "country":"Italia"},
        {"name" : "George Russell", "country":"Great Britain"},
        {"name" : "Fernando Alonso", "country":"Spain"},
        {"name" : "Lance Stroll", "country":"Canada"},
        {"name" : "Charles Leclerc", "country":"Monaco"},
        {"name" : "Arthur Leclerc", "country":"Monaco"},
        {"name" : "Lewis Hamilton", "country":"Great Britain"},
        {"name" : "Alexander Albon", "country":"Thailand"},
        {"name" : "Carlos Sainz", "country":"Spain"},
        {"name" : "Nico Hulkenberg", "country":"Germany"},
        {"name" : "Gabriel Bortoleto", "country":"Brazil"},
        {"name" : "Liam Lawson", "country":"New Zealand"},
        {"name" : "Isack Hadjar", "country":"France"},
        {"name" : "Esteban Ocon", "country":"France"},
        {"name" : "Oliver Bearman", "country":"Great Britain"},
        {"name" : "Lando Norris", "country":"Great Britain"},
        {"name" : "Oscar Piastri", "country":"Australia"},
        {"name" : "Cian Shields", "country":"Great Britain"},
        {"name" : "Jak Crawford", "country":"America"},
        {"name" : "Patricio O'Ward", "country":"Mexico"},
        {"name" : "Ayumu Iwasa", "country":"Japan"},
        {"name" : "Paul Aron", "country":"Estonia"},
        {"name" : "Luke Browning", "country":"Great Britain"},
        {"name" : "Ryo Hirakawa", "country":"Japan"},
        {"name" : "Frederik Vesti", "country":"Danemark"},
        {"name" : "Antonio Fuoco", "country":"Italia"},
        {"name" : "Alexander Dunne", "country":"Ireland"},
        {"name" : "Felipe Drugovich", "country":"Brazil"},
        {"name" : "Dino Beganovic", "country":"Sweden"},
        {"name" : "Jack Doohan", "country":"Australia"},
        ]
drivers_data_manual = pd.DataFrame(drivers_data_manual)
drivers_all_info = pd.merge(df_final, drivers_data_manual, how='outer', on='name')
drivers_all_info = drivers_all_info.drop_duplicates(['abbreviation'])
drivers_all_info = drivers_all_info.drop_duplicates(['name'], keep='first')
drivers_records = drivers_all_info.to_dict('records')

teams = fastf1.plotting.list_team_names(session)
teams = [{"name":team, "hex_code":fastf1.plotting.get_team_color(team, session)} for team in teams]
df = pd.DataFrame(teams)
teams = [{"name": "Alpine", "abbreviation": "ALP", "country":"France"},
        {"name": "Aston Martin", "abbreviation": "AMR", "country":"Great Britain"},
        {"name": "Ferrari", "abbreviation": "FER", "country":"Italia"},
        {"name": "Haas F1 Team", "abbreviation": "HAA", "country":"America"},
        {"name": "Kick Sauber", "abbreviation": "SAU", "country":"Switz"},
        {"name": "McLaren", "abbreviation": "MCL", "country":"New Zealand"},
        {"name": "Mercedes", "abbreviation": "MER", "country":"German"},
        {"name": "Racing Bulls", "abbreviation": "RBL", "country":"Italia"},
        {"name": "Red Bull Racing", "abbreviation": "RBR", "country":"Great Britain"},
        {"name": "Williams", "abbreviation": "WIL", "country":"Great Britain"},
        ]
df_manual_insert = pd.DataFrame(teams)
df_teams = pd.merge(df, df_manual_insert, how='outer', on='name').drop_duplicates()
teams_records = df_teams.to_dict('records')
clear_output()

In [14]:
print(len(teams_records))
teams_records

10

[{'name': 'Alpine',
  'hex_code': '#ff87bc',
  'abbreviation': 'ALP',
  'country': 'France'},
 {'name': 'Aston Martin',
  'hex_code': '#00665f',
  'abbreviation': 'AMR',
  'country': 'Great Britain'},
 {'name': 'Ferrari',
  'hex_code': '#e80020',
  'abbreviation': 'FER',
  'country': 'Italia'},
 {'name': 'Haas F1 Team',
  'hex_code': '#b6babd',
  'abbreviation': 'HAA',
  'country': 'America'},
 {'name': 'Kick Sauber',
  'hex_code': '#00e700',
  'abbreviation': 'SAU',
  'country': 'Switz'},
 {'name': 'McLaren',
  'hex_code': '#ff8000',
  'abbreviation': 'MCL',
  'country': 'New Zealand'},
 {'name': 'Mercedes',
  'hex_code': '#27f4d2',
  'abbreviation': 'MER',
  'country': 'German'},
 {'name': 'Racing Bulls',
  'hex_code': '#fcd700',
  'abbreviation': 'RBL',
  'country': 'Italia'},
 {'name': 'Red Bull Racing',
  'hex_code': '#0600ef',
  'abbreviation': 'RBR',
  'country': 'Great Britain'},
 {'name': 'Williams',
  'hex_code': '#00a0dd',
  'abbreviation': 'WIL',
  'country': 'Great Britain'}]

In [15]:
print(len(drivers_records))
drivers_records

35

[{'number': '23',
  'abbreviation': 'ALB',
  'name': 'Alexander Albon',
  'hex_code': '1868DB',
  'country': 'Thailand'},
 {'number': '89',
  'abbreviation': 'DUN',
  'name': 'Alexander Dunne',
  'hex_code': 'F47600',
  'country': 'Ireland'},
 {'number': '12',
  'abbreviation': 'ANT',
  'name': 'Andrea Kimi Antonelli',
  'hex_code': '27F4D2',
  'country': nan},
 {'number': '38',
  'abbreviation': 'FUO',
  'name': 'Antonio Fuoco',
  'hex_code': 'ED1131',
  'country': 'Italia'},
 {'number': '39',
  'abbreviation': 'LEL',
  'name': 'Arthur Leclerc',
  'hex_code': 'ED1131',
  'country': 'Monaco'},
 {'number': '36',
  'abbreviation': 'LIN',
  'name': 'Arvid Lindblad',
  'hex_code': '4781D7',
  'country': 'Great Britain'},
 {'number': '40',
  'abbreviation': 'IWA',
  'name': 'Ayumu Iwasa',
  'hex_code': '6C98FF',
  'country': 'Japan'},
 {'number': '55',
  'abbreviation': 'SAI',
  'name': 'Carlos Sainz',
  'hex_code': '1868DB',
  'country': 'Spain'},
 {'number': '16',
  'abbreviation': 'LEC',
  'name': 'Charles Leclerc',
  'hex_code': 'ED1131',
  'country': 'Monaco'},
 {'number': '34',
  'abbreviation': 'SHI',
  'name': 'Cian Shields',
  'hex_code': '229971',
  'country': 'Great Britain'},
 {'number': '38',
  'abbreviation': 'BEG',
  'name': 'Dino Beganovic',
  'hex_code': 'ED1131',
  'country': 'Sweden'},
 {'number': '31',
  'abbreviation': 'OCO',
  'name': 'Esteban Ocon',
  'hex_code': '9C9FA2',
  'country': 'France'},
 {'number': '34',
  'abbreviation': 'DRU',
  'name': 'Felipe Drugovich',
  'hex_code': '229971',
  'country': 'Brazil'},
 {'number': '14',
  'abbreviation': 'ALO',
  'name': 'Fernando Alonso',
  'hex_code': '229971',
  'country': 'Spain'},
 {'number': '43',
  'abbreviation': 'COL',
  'name': 'Franco Colapinto',
  'hex_code': '00A1E8',
  'country': 'Argentine'},
 {'number': '72',
  'abbreviation': 'VES',
  'name': 'Frederik Vesti',
  'hex_code': '00D7B6',
  'country': 'Danemark'},
 {'number': '5',
  'abbreviation': 'BOR',
  'name': 'Gabriel Bortoleto',
  'hex_code': '01C00E',
  'country': 'Brazil'},
 {'number': '63',
  'abbreviation': 'RUS',
  'name': 'George Russell',
  'hex_code': '00D7B6',
  'country': 'Great Britain'},
 {'number': '6',
  'abbreviation': 'HAD',
  'name': 'Isack Hadjar',
  'hex_code': '6C98FF',
  'country': 'France'},
 {'number': '7',
  'abbreviation': 'DOO',
  'name': 'Jack Doohan',
  'hex_code': '0093CC',
  'country': 'Australia'},
 {'number': '35',
  'abbreviation': 'CRA',
  'name': 'Jak Crawford',
  'hex_code': '229971',
  'country': 'America'},
 {'number': '18',
  'abbreviation': 'STR',
  'name': 'Lance Stroll',
  'hex_code': '229971',
  'country': 'Canada'},
 {'number': '4',
  'abbreviation': 'NOR',
  'name': 'Lando Norris',
  'hex_code': 'F47600',
  'country': 'Great Britain'},
 {'number': '44',
  'abbreviation': 'HAM',
  'name': 'Lewis Hamilton',
  'hex_code': 'ED1131',
  'country': 'Great Britain'},
 {'number': '30',
  'abbreviation': 'LAW',
  'name': 'Liam Lawson',
  'hex_code': '6C98FF',
  'country': 'New Zealand'},
 {'number': '46',
  'abbreviation': 'BRO',
  'name': 'Luke Browning',
  'hex_code': '1868DB',
  'country': 'Great Britain'},
 {'number': '1',
  'abbreviation': 'VER',
  'name': 'Max Verstappen',
  'hex_code': '4781D7',
  'country': 'Dutchland'},
 {'number': '27',
  'abbreviation': 'HUL',
  'name': 'Nico Hulkenberg',
  'hex_code': '01C00E',
  'country': 'Germany'},
 {'number': '87',
  'abbreviation': 'BEA',
  'name': 'Oliver Bearman',
  'hex_code': '9C9FA2',
  'country': 'Great Britain'},
 {'number': '81',
  'abbreviation': 'PIA',
  'name': 'Oscar Piastri',
  'hex_code': 'F47600',
  'country': 'Australia'},
 {'number': '89',
  'abbreviation': 'OWA',
  'name': "Patricio O'Ward",
  'hex_code': 'F47600',
  'country': 'Mexico'},
 {'number': '61',
  'abbreviation': 'ARO',
  'name': 'Paul Aron',
  'hex_code': '00A1E8',
  'country': 'Estonia'},
 {'number': '10',
  'abbreviation': 'GAS',
  'name': 'Pierre Gasly',
  'hex_code': '00A1E8',
  'country': 'France'},
 {'number': '50',
  'abbreviation': 'HIR',
  'name': 'Ryo Hirakawa',
  'hex_code': '9C9FA2',
  'country': 'Japan'},
 {'number': '22',
  'abbreviation': 'TSU',
  'name': 'Yuki Tsunoda',
  'hex_code': '4781D7',
  'country': 'Japan'}]

In [5]:
import fastf1

schedule = fastf1.get_event_schedule(2025, include_testing=False)
event_round = schedule[["RoundNumber", "Country", "Location", "EventName", "EventDate", "EventFormat"]].copy()
event_round.loc[event_round["EventFormat"] == "sprint_qualifying", "IsSprintEvent"] = 1
event_round["IsSprintEvent"] = event_round["IsSprintEvent"].fillna(0).astype(bool)
event_round["Year"] = 2025
event_round = event_round.drop(labels='EventFormat', axis=1)
print(event_round.columns)
event_round = event_round.rename(columns={
                            "RoundNumber" : "round_number",
                            "Country": "country",
                            "Location": "location",
                            "EventName": "name",
                            "EventDate": "date",
                            "IsSprintEvent": "is_sprint_event",
                            "Year": "year"})
event_round

Index(['RoundNumber', 'Country', 'Location', 'EventName', 'EventDate',
       'IsSprintEvent', 'Year'],
      dtype='object')

,round_number,country,location,name,date,is_sprint_event,year
1,1,Australia,Melbourne,Australian Grand Prix,2025-03-16,False,2025
2,2,China,Shanghai,Chinese Grand Prix,2025-03-23,True,2025
3,3,Japan,Suzuka,Japanese Grand Prix,2025-04-06,False,2025
4,4,Bahrain,Sakhir,Bahrain Grand Prix,2025-04-13,False,2025
5,5,Saudi Arabia,Jeddah,Saudi Arabian Grand Prix,2025-04-20,False,2025
6,6,United States,Miami Gardens,Miami Grand Prix,2025-05-04,True,2025
7,7,Italy,Imola,Emilia Romagna Grand Prix,2025-05-18,False,2025
8,8,Monaco,Monaco,Monaco Grand Prix,2025-05-25,False,2025
9,9,Spain,Barcelona,Spanish Grand Prix,2025-06-01,False,2025
10,10,Canada,Montréal,Canadian Grand Prix,2025-06-15,False,2025
11,11,Austria,Spielberg,Austrian Grand Prix,2025-06-29,False,2025
12,12,United Kingdom,Silverstone,British Grand Prix,2025-07-06,False,2025
13,13,Belgium,Spa-Francorchamps,Belgian Grand Prix,2025-07-27,True,2025
14,14,Hungary,Budapest,Hungarian Grand Prix,2025-08-03,False,2025
15,15,Netherlands,Zandvoort,Dutch Grand Prix,2025-08-31,False,2025
16,16,Italy,Monza,Italian Grand Prix,2025-09-07,False,2025
17,17,Azerbaijan,Baku,Azerbaijan Grand Prix,2025-09-21,False,2025
18,18,Singapore,Marina Bay,Singapore Grand Prix,2025-10-05,False,2025
19,19,United States,Austin,United States Grand Prix,2025-10-19,True,2025
20,20,Mexico,Mexico City,Mexico City Grand Prix,2025-10-26,False,2025
21,21,Brazil,São Paulo,São Paulo Grand Prix,2025-11-09,True,2025
22,22,United States,Las Vegas,Las Vegas Grand Prix,2025-11-22,False,2025
23,23,Qatar,Lusail,Qatar Grand Prix,2025-11-30,True,2025
24,24,United Arab Emirates,Yas Island,Abu Dhabi Grand Prix,2025-12-07,False,2025

In [ ]:
from  database.modules.tyres_info import get_tyres_info
import os
from dotenv import load_dotenv
load_dotenv()

schedule = fastf1.get_event_schedule(2025, include_testing=False)
event_round = schedule[["RoundNumber", "Country", "Location", "EventName", "EventDate", "EventFormat"]].copy()
event_round.loc[event_round["EventFormat"] == "sprint_qualifying", "IsSprintEvent"] = 1
event_round["IsSprintEvent"] = event_round["IsSprintEvent"].fillna(0).astype(bool)
event_round["Year"] = 2025
event_round = event_round.drop(labels='EventFormat', axis=1)
event_round = event_round.rename(columns={
                            "RoundNumber" : "round_number",
                            "Country": "country",
                            "Location": "location",
                            "EventName": "name",
                            "EventDate": "date",
                            "IsSprintEvent": "is_sprint_event",
                            "Year": "year"})


tyres_df = get_tyres_info(os.getenv('ROUND'), schedule)

event_round = event_round.merge(tyres_df, left_on="name", right_index=True, how="left")
event_round = event_round[['name', 'round_number', 'year', 'date', 'country', 'location', 'is_sprint_event', 'soft', 'medium', 'hard']]
event_round[['soft', 'medium', 'hard']] = 'C' + event_round[['soft', 'medium', 'hard']].astype(str)
event_round_records = event_round.to_dict('records')
print(event_round_records)

ModuleNotFoundError: No module named 'database'

In [1]:
import fastf1
fastf1.get_event_schedule(2025, include_testing=False)

req         WARNING 	DEFAULT CACHE ENABLED! (32.54 GB) /home/kurios/.cache/fastf1

,RoundNumber,Country,Location,OfficialEventName,EventDate,EventName,EventFormat,Session1,Session1Date,Session1DateUtc,...,Session3,Session3Date,Session3DateUtc,Session4,Session4Date,Session4DateUtc,Session5,Session5Date,Session5DateUtc,F1ApiSupport
1,1,Australia,Melbourne,FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...,2025-03-16,Australian Grand Prix,conventional,Practice 1,2025-03-14 12:30:00+11:00,2025-03-14 01:30:00,...,Practice 3,2025-03-15 12:30:00+11:00,2025-03-15 01:30:00,Qualifying,2025-03-15 16:00:00+11:00,2025-03-15 05:00:00,Race,2025-03-16 15:00:00+11:00,2025-03-16 04:00:00,True
2,2,China,Shanghai,FORMULA 1 HEINEKEN CHINESE GRAND PRIX 2025,2025-03-23,Chinese Grand Prix,sprint_qualifying,Practice 1,2025-03-21 11:30:00+08:00,2025-03-21 03:30:00,...,Sprint,2025-03-22 11:00:00+08:00,2025-03-22 03:00:00,Qualifying,2025-03-22 15:00:00+08:00,2025-03-22 07:00:00,Race,2025-03-23 15:00:00+08:00,2025-03-23 07:00:00,True
3,3,Japan,Suzuka,FORMULA 1 LENOVO JAPANESE GRAND PRIX 2025,2025-04-06,Japanese Grand Prix,conventional,Practice 1,2025-04-04 11:30:00+09:00,2025-04-04 02:30:00,...,Practice 3,2025-04-05 11:30:00+09:00,2025-04-05 02:30:00,Qualifying,2025-04-05 15:00:00+09:00,2025-04-05 06:00:00,Race,2025-04-06 14:00:00+09:00,2025-04-06 05:00:00,True
4,4,Bahrain,Sakhir,FORMULA 1 GULF AIR BAHRAIN GRAND PRIX 2025,2025-04-13,Bahrain Grand Prix,conventional,Practice 1,2025-04-11 14:30:00+03:00,2025-04-11 11:30:00,...,Practice 3,2025-04-12 15:30:00+03:00,2025-04-12 12:30:00,Qualifying,2025-04-12 19:00:00+03:00,2025-04-12 16:00:00,Race,2025-04-13 18:00:00+03:00,2025-04-13 15:00:00,True
5,5,Saudi Arabia,Jeddah,FORMULA 1 STC SAUDI ARABIAN GRAND PRIX 2025,2025-04-20,Saudi Arabian Grand Prix,conventional,Practice 1,2025-04-18 16:30:00+03:00,2025-04-18 13:30:00,...,Practice 3,2025-04-19 16:30:00+03:00,2025-04-19 13:30:00,Qualifying,2025-04-19 20:00:00+03:00,2025-04-19 17:00:00,Race,2025-04-20 20:00:00+03:00,2025-04-20 17:00:00,True
6,6,United States,Miami Gardens,FORMULA 1 CRYPTO.COM MIAMI GRAND PRIX 2025,2025-05-04,Miami Grand Prix,sprint_qualifying,Practice 1,2025-05-02 12:30:00-04:00,2025-05-02 16:30:00,...,Sprint,2025-05-03 12:00:00-04:00,2025-05-03 16:00:00,Qualifying,2025-05-03 16:00:00-04:00,2025-05-03 20:00:00,Race,2025-05-04 16:00:00-04:00,2025-05-04 20:00:00,True
7,7,Italy,Imola,FORMULA 1 AWS GRAN PREMIO DEL MADE IN ITALY E ...,2025-05-18,Emilia Romagna Grand Prix,conventional,Practice 1,2025-05-16 13:30:00+02:00,2025-05-16 11:30:00,...,Practice 3,2025-05-17 12:30:00+02:00,2025-05-17 10:30:00,Qualifying,2025-05-17 16:00:00+02:00,2025-05-17 14:00:00,Race,2025-05-18 15:00:00+02:00,2025-05-18 13:00:00,True
8,8,Monaco,Monaco,FORMULA 1 TAG HEUER GRAND PRIX DE MONACO 2025,2025-05-25,Monaco Grand Prix,conventional,Practice 1,2025-05-23 13:30:00+02:00,2025-05-23 11:30:00,...,Practice 3,2025-05-24 12:30:00+02:00,2025-05-24 10:30:00,Qualifying,2025-05-24 16:00:00+02:00,2025-05-24 14:00:00,Race,2025-05-25 15:00:00+02:00,2025-05-25 13:00:00,True
9,9,Spain,Barcelona,FORMULA 1 ARAMCO GRAN PREMIO DE ESPAÑA 2025,2025-06-01,Spanish Grand Prix,conventional,Practice 1,2025-05-30 13:30:00+02:00,2025-05-30 11:30:00,...,Practice 3,2025-05-31 12:30:00+02:00,2025-05-31 10:30:00,Qualifying,2025-05-31 16:00:00+02:00,2025-05-31 14:00:00,Race,2025-06-01 15:00:00+02:00,2025-06-01 13:00:00,True
10,10,Canada,Montréal,FORMULA 1 PIRELLI GRAND PRIX DU CANADA 2025,2025-06-15,Canadian Grand Prix,conventional,Practice 1,2025-06-13 13:30:00-04:00,2025-06-13 17:30:00,...,Practice 3,2025-06-14 12:30:00-04:00,2025-06-14 16:30:00,Qualifying,2025-06-14 16:00:00-04:00,2025-06-14 20:00:00,Race,2025-06-15 14:00:00-04:00,2025-06-15 18:00:00,True
11,11,Austria,Spielberg,FORMULA 1 MSC CRUISES AUSTRIAN GRAND PRIX 2025,2025-06-29,Austrian Grand Prix,conventional,Practice 1,2025-06-27 13:30:00+02:00,2025-06-27 11:30:00,...,Practice 3,2025-06-28 12:30:00+02:00,2025-06-28 10:30:00,Qualifying,2025-06-28 16:00:00+02:00,2025-06-28 14:00:00,Race,2025-06-29 15:00:00+02:00,2025-06-29 13:00:00,True
12,12,United Kingdom,Silverstone,FORMULA 1 QATAR AIRWAYS BRITISH GRAND PRIX 2025,2025-07-06,British Grand Prix,conventional,Practice 1,2025-07-04 12:30:00+01:00,2025-07-04 11:30:00,...,Practice 3,2025-07-05 11:30:00+01:00,2025-07-05 10:30:00,Qualifying,2025-07-05 15:00:00+01:00,2025-07-05 14:00:00,Race,2025-07-06 15:00:00+01:00,2025-07-06 14:00:00,True
13,13,Belgium,Spa-Francorchamps,FORMULA 1 MOËT & CHANDON BELGIAN GRAND PRIX 2025,2025-07-27,Belgian Grand Prix,sprint_qualifying,Practice 1,2025-07-25 12:30:00+02:00,2025-07-25 10:30:00,...,Sprint,2025-07-26 12:00:00+02:00,2025-07-26 10:00:00,Qualifying,2025-07-26 16:00:00+02:00,2025-07-26 14:00:00,Race,2025-07-27 15:00:00+02:00,2025-07-27 13:00:00,True
14,14,Hungary,Budapest,FORMULA 1 LENOVO HUNGARIAN GRAND PRIX 2025,2025-08-03,Hungarian Grand Prix,conventional,Practice 1,2025-08-01 13:30:00+02:00,2025-08-01 11:30:00,...,Practice 3,2025-08-02 12:30:00+02:00,2025-08-02 10:30:00,Qualifying,2025-08-02 16:00:00+02:00,2025-08-02 14:00:00,Race,2025-08-03 15:00:00+02:00,2025-08-03 13:00:00,True
15,15,Netherlands,Zandvoort,FORMULA 1 HEINEKEN DUTCH GRAND PRIX 2025,2025-08-31,Dutch Grand Prix,conventional,Practice 1,2025-08-29 12:30:00+02:00,2025-08-29 10:30:00,...,Practice 3,2025-08-30 11:30:00+02:00,2025-08-30 09:30:00,Qualifying,2025-08-30 15:00:00+02:00,2025-08-30 13:00:00,Race,2025-08-31 15:00:00+02:00,2025-08-31 13:00:00,True
16,16,Italy,Monza,FORMULA 1 PIRELLI GRAN PREMIO D’ITALIA 2025,2025-09-07,Italian Grand Prix,conventional,Practice 1,2025-09-05 13:30:00+02:00,2025-09-05 11:30:00,...,Practice 3,2025-09-06 12:30:00+02:00,2025-09-06 10:30:00,Qualifying,2025-09-06 16:00:00+02:00,2025-09-06 14:00:00,Race,2025-09-07 15:00:00+02:00,2025-09-07 13:00:00,True
17,17,Azerbaijan,Baku,FORMULA 1 QATAR AIRWAYS AZERBAIJAN GRAND PRIX ...,2025-09-21,Azerbaijan Grand Prix,conventional,Practice 1,2025-09-19 12:30:00+04:00,2025-09-19 08:30:00,...,Practice 3,2025-09-20 12:30:00+04:00,2025-09-20 08:30:00,Qualifying,2025-09-20 16:00:00+04:00,2025-09-20 12:00:00,Race,2025-09-21 15:00:00+04:00,2025-09-21 11:00:00,True
18,18,Singapore,Marina Bay,FORMULA 1 SINGAPORE AIRLINES SINGAPORE GRAND P...,2025-10-05,Singapore Grand Prix,conventional,Practice 1,2025-10-03 17:30:00+08:00,2025-10-03 09:30:00,...,Practice 3,2025-10-04 17:30:00+08:00,2025-10-04 09:30:00,Qualifying,2025-10-04 21:00:00+08:00,2025-10-04 13:00:00,Race,2025-10-05 20:00:00+08:00,2025-10-05 12:00:00,True
19,19,United States,Austin,FORMULA 1 MSC CRUISES UNITED STATES GRAND PRIX...,2025-10-19,United States Grand Prix,sprint_qualifying,Practice 1,2025-10-17 12:30:00-05:00,2025-10-17 17:30:00,...,Sprint,2025-10-18 12:00:00-05:00,2025-10-18 17:00:00,Qualifying,2025-10-18 16:00:00-05:00,2025-10-18 21:00:00,Race,2025-10-19 14:00:00-05:00,2025-10-19 19:00:00,True
20,20,Mexico,Mexico City,FORMULA 1 GRAN PREMIO DE LA CIUDAD DE MÉXICO 2025,2025-10-26,Mexico City Grand Prix,conventional,Practice 1,2025-10-24 12:30:00-06:00,2025-10-24 18:30:00,...,Practice 3,2025-10-25 11:30:00-06:00,2025-10-25 17:30:00,Qualifying,2025-10-25 15:00:00-06:00,2025-10-25 21:00:00,Race,2025-10-26 14:00:00-06:00,2025-10-26 20:00:00,True
21,21,Brazil,São Paulo,FORMULA 1 MSC CRUISES GRANDE PRÊMIO DE SÃO PAU...,2025-11-09,São Paulo Grand Prix,sprint_qualifying,Practice 1,2025-11-07 11:30:00-03:00,2025-11-07 14:30:00,...,Sprint,2025-11-08 11:00:00-03:00,2025-11-08 14:00:00,Qualifying,2025-11-08 15:00:00-03:00,2025-11-08 18:00:00,Race,2025-11-09 14:00:00-03:00,2025-11-09 17:00:00,True
22,22,United States,Las Vegas,FORMULA 1 HEINEKEN LAS VEGAS GRAND PRIX 2025,2025-11-22,Las Vegas Grand Prix,conventional,Practice 1,2025-11-20 16:30:00-08:00,2025-11-21 00:30:00,...,Practice 3,2025-11-21 16:30:00-08:00,2025-11-22 00:30:00,Qualifying,2025-11-21 20:00:00-08:00,2025-11-22 04:00:00,Race,2025-11-22 20:00:00-08:00,2025-11-23 04:00:00,True
23,23,Qatar,Lusail,FORMULA 1 QATAR AIRWAYS QATAR GRAND PRIX 2025,2025-11-30,Qatar Grand Prix,sprint_qualifying,Practice 1,2025-11-28 16:30:00+03:00,2025-11-28 13:30:00,...,Sprint,2025-11-29 17:00:00+03:00,2025-11-29 14:00:00,Qualifying,2025-11-29 21:00:00+03:00,2025-11-29 18:00:00,Race,2025-11-30 19:00:00+03:00,2025-11-30 16:00:00,True
24,24,United Arab Emirates,Yas Island,FORMULA 1 ETIHAD AIRWAYS ABU DHABI GRAND PRIX ...,2025-12-07,Abu Dhabi Grand Prix,conventional,Practice 1,2025-12-05 13:30:00+04:00,2025-12-05 09:30:00,...,Practice 3,2025-12-06 14:30:00+04:00,2025-12-06 10:30:00,Qualifying,2025-12-06 18:00:00+04:00,2025-12-06 14:00:00,Race,2025-12-07 17:00:00+04:00,2025-12-07 13:00:00,True

In [14]:
import requests
import fastf1
import re
from concurrent.futures import ThreadPoolExecutor, as_completed
import pandas as pd

def get_tyre_info_api(year , event_name, session):
    event_url_name = re.sub(r'\s+', '_', event_name.strip())
    
    api_url = f"https://en.wikipedia.org/w/api.php?action=query&prop=revisions&titles={year}_{event_url_name}&rvprop=content&format=json&formatversion=2"

    try:
        response = session.get(api_url, timeout=10)
        response.raise_for_status()
        data = response.json()

        if 'pages' in data['query'] and 'missing' not in data['query']['pages'][0]:
            page_content = data['query']['pages'][0]['revisions'][0]['content']
             
            tyre_section_match = re.search(r'==\s*Tyre choices\s*==(.*?)==', page_content, re.DOTALL)
            if tyre_section_match:
                tyre_section_content = tyre_section_match.group(1)
                found_compound_levels = set()
                pattern = re.compile(r'C[1-6]')
                matches_with_C = pattern.findall(tyre_section_content)
                matches = list(map(lambda i: i[1:], matches_with_C))

                if matches:
                    found_compound_levels.update(matches)

                compound_levels_list = sorted(list(found_compound_levels))
                if len(compound_levels_list) == 3:
                    return event_name, compound_levels_list
                else:
                    found_compound_levels_fallback = set()
                    matches_fallback = pattern.findall(page_content)
                    if matches_fallback:
                        found_compound_levels_fallback.update(matches_fallback)
                    
                    compound_levels_list_fallback = sorted(list(found_compound_levels_fallback), key=lambda x: int(x[1:]))

                    if len(compound_levels_list_fallback) >= 3:
                        return event_name, compound_levels_list_fallback[:3]
                    else:
                        return event_name, ['0', '0', '0']
            else:
                return event_name, ['0', '0', '0']
        else:
            return event_name, ['0', '0', '0']
             
    except (requests.exceptions.RequestException, Exception) as err:
        print(f"Error for {event_name}: {err}. Setting default values.")
        return event_name, ['0', '0', '0']

schedule = fastf1.get_event_schedule(2025, include_testing=False)
event_round = schedule[["RoundNumber", "Country", "Location", "EventName", "EventDate", "EventFormat"]].copy()
event_round.loc[event_round["EventFormat"] == "sprint_qualifying", "IsSprintEvent"] = 1
event_round["IsSprintEvent"] = event_round["IsSprintEvent"].fillna(0).astype(bool)
event_round["Year"] = 2025
event_round = event_round.drop(labels='EventFormat', axis=1)
event_round = event_round.rename(columns={
                            "RoundNumber" : "round_number",
                            "Country": "country",
                            "Location": "location",
                            "EventName": "name",
                            "EventDate": "date",
                            "IsSprintEvent": "is_sprint_event",
                            "Year": "year"})

def get_tyres_info():
    tyres = {}
    session = requests.Session()
    session.headers.update({
        'User-Agent': 'tyre_compound/1.0 (cyril.leconte07@gmail.com)'
    })

    with ThreadPoolExecutor(max_workers=24) as executor:
        future_to_event = {executor.submit(get_tyre_info_api, 2025, event, session): event for event in schedule.EventName}
        
        for future in as_completed(future_to_event):
            event_name, c_levels = future.result()
            tyres[event_name] = c_levels

    tyres_df = pd.DataFrame.from_dict(columns=['hard', 'medium', 'soft'], data = tyres, orient="index")
    return tyres_df

tyres_df = get_tyres_info()
tyres_df
'''
event_round = event_round.merge(tyres_df, left_on="name", right_index=True, how="left")
event_round = event_round[['name', 'round_number', 'year', 'date', 'country', 'location', 'is_sprint_event', 'soft', 'medium', 'hard']]
event_round[['soft', 'medium', 'hard']] = 'C' + event_round[['soft', 'medium', 'hard']].astype(str)
event_round_records = event_round.to_dict('records')
event_round_records'''

from sqlalchemy import select
from sqlalchemy.orm import relationship
from sqlalchemy import Column, Integer, String, Date, Boolean, ForeignKey, SmallInteger, Text, Interval, Float
from sqlalchemy.orm import declarative_base

Base = declarative_base()
class Compound(Base):
    __tablename__ = 'compound'

    id = Column(Integer, primary_key=True)
    hardness = Column(String(2), nullable=False, unique=True)

    event_round_soft = relationship('EventRound', back_populates='soft_compound', foreign_keys='EventRound.soft_compound_id')

    event_round_medium = relationship('EventRound', back_populates='medium_compound', foreign_keys='EventRound.medium_compound_id')

    event_round_hard = relationship('EventRound', back_populates='hard_compound', foreign_keys='EventRound.hard_compound_id')

def get_or_create_compound(session, hardness: str) -> Compound:
    compound = session.execute(
        select(Compound).where(Compound.hardness == hardness)
    ).scalar_one_or_none()

    if compound is None:
        compound = Compound(hardness=hardness)
        session.add(compound)
        session.flush()

    return compound

compound_cache = {}

def get_cached_compound(session, hardness):
    if hardness not in compound_cache:
        compound_cache[hardness] = get_or_create_compound(session, hardness)
    return compound_cache[hardness]

def map_to_compound(hardness):
    return get_cached_compound(session, hardness)

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from dotenv import load_dotenv
import os

load_dotenv()


ENGINE = create_engine(f"sqlite:/// backend/database/data/f1_analysis.db", echo=True)
Session = sessionmaker(bind=ENGINE)

with Session() as session:
    tyres_df = tyres_df.map(map_to_compound)
    tyres_df

OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [13]:
event = fastf1.get_event(2025, 1)
print(event)
print(event.Session1)
print(event.Session1Date.date())
print(event.EventDate.date())

RoundNumber                                                          1
Country                                                      Australia
Location                                                     Melbourne
OfficialEventName    FORMULA 1 LOUIS VUITTON AUSTRALIAN GRAND PRIX ...
EventDate                                          2025-03-16 00:00:00
EventName                                        Australian Grand Prix
EventFormat                                               conventional
Session1                                                    Practice 1
Session1Date                                 2025-03-14 12:30:00+11:00
Session1DateUtc                                    2025-03-14 01:30:00
Session2                                                    Practice 2
Session2Date                                 2025-03-14 16:00:00+11:00
Session2DateUtc                                    2025-03-14 05:00:00
Session3                                                    Practice 3
Session3Date                                 2025-03-15 12:30:00+11:00
Session3DateUtc                                    2025-03-15 01:30:00
Session4                                                    Qualifying
Session4Date                                 2025-03-15 16:00:00+11:00
Session4DateUtc                                    2025-03-15 05:00:00
Session5                                                          Race
Session5Date                                 2025-03-16 15:00:00+11:00
Session5DateUtc                                    2025-03-16 04:00:00
F1ApiSupport                                                      True
Name: 1, dtype: object
Practice 1
2025-03-14
2025-03-16

In [7]:
event.Session1

'Practice 1'

In [6]:
sess = event.get_session(1)
sess

2025 Season Round 1: Australian Grand Prix - Practice 1